
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "devsarvesh92", email = "sarveshdev92@gmail.com"},
]
dependencies = [
    "pytest>=7.4.0",
    "python-benedict[all]>=0.33.0",
]
requires-python = ">=3.11"
license = {text = "MIT"}
